[package]
name = "tntnt"
version = "0.0.0"
authors = ["WHMHammer <whmhammer@gmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/WHMHammer/TNTNT"
license = "GPL-3.0-or-later"
keywords = ["game"]
categories = ["games"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "*"
rodio = "*"
